version: "2.1"

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
  grafana-config:
  certbot-etc:/etc/letsencrypt
  certbot-var:/var/lib/letsencrypt
  ssl:/etc/grafana/ssl

services:
  influxdb:
    build: services/influxdb
    privileged: true
    ports:
      - '8086:8086'
      - '25826:25826/udp'
    volumes:
       - influxdb-config:/etc/influxdb/
       - influxdb-data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    build: services/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana/
      - grafana-config:/etc/grafana/
    restart: unless-stopped
    environment:
      - GF_SERVER_PROTOCOL=${GF_SERVER_PROTOCOL}
      - GF_SERVER_CERT_FILE=${GF_SERVER_CERT_FILE}
      - GF_SERVER_CERT_KEY=${GF_SERVER_CERT_KEY}
    volumes:
      - grafana-data:/var/lib/grafana/
      - grafana-config:/etc/grafana/
      - ./ssl:/etc/grafana/ssl

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos -d ${CERTBOT_DOMAIN}
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    deploy:
      replicas: 1
    entrypoint: /bin/sh -c "trap : TERM INT; sleep infinity & wait"