version: "2.1"

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
  grafana-config:
 
services:
  influxdb:
    build: services/influxdb
    privileged: true
    ports:
      - '8086:8086'
      - '25826:25826/udp'
    volumes:
       - influxdb-config:/etc/influxdb/
       - influxdb-data:/var/lib/influxdb
    restart: unless-stopped
  grafana:
    build: services/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana/
      - grafana-config:/etc/grafana/
    restart: unless-stopped
     
    